<?php

namespace ArtARTs36\PushAllSender\Tests\Unit;

use ArtARTs36\PushAllSender\Exceptions\PushIncorrectPriorityException;
use ArtARTs36\PushAllSender\Interfaces\PushRecipientInterface;
use ArtARTs36\PushAllSender\Push;
use ArtARTs36\PushAllSender\Strategies\RecipientFriendlyStrategy\NightMinPriorityStrategy;
use ArtARTs36\PushAllSender\Strategies\RecipientFriendlyStrategy\RecipientFriendlyStrategyInterface;
use PHPUnit\Framework\TestCase;

/**
 * Class PushTest
 * @package ArtARTs36\PushAllSender\Tests\Unit
 */
class PushTest extends TestCase
{
    /**
     * @covers \ArtARTs36\PushAllSender\Push::setRecipientFriendlyPriority
     * @throws \ArtARTs36\PushAllSender\Exceptions\PushException
     */
    public function testSetIncorrectRecipientFriendlyPriority(): void
    {
        $strategy = new class implements RecipientFriendlyStrategyInterface {
            public function getPriority(): int
            {
                return 10;
            }
        };

        self::expectException(PushIncorrectPriorityException::class);

        $this->makePush()->setRecipientFriendlyPriority($strategy);
    }

    /**
     * @covers \ArtARTs36\PushAllSender\Push::setPriority
     */
    public function testCheckPriority(): void
    {
        $push = new class('Title', 'Message') extends Push {
            public function checkPriority(int $priority): bool
            {
                return parent::checkPriority($priority); // TODO: Change the autogenerated stub
            }
        };

        //

        self::assertFalse($push->checkPriority(15));

        //

        self::assertTrue($push->checkPriority(Push::PRIORITY_MIDDLE));
        self::assertTrue($push->checkPriority(Push::PRIORITY_MIN));
        self::assertTrue($push->checkPriority(Push::PRIORITY_MAX));
    }

    /**
     * @covers \ArtARTs36\PushAllSender\Push::setMaxPriority
     */
    public function testSetMaxPriority(): void
    {
        $push = $this->makePush()->setMaxPriority();

        self::assertEquals(Push::PRIORITY_MAX, $push->getPriority());
    }

    /**
     * @covers \ArtARTs36\PushAllSender\Push::setMiddlePriority
     * @throws \ArtARTs36\PushAllSender\Exceptions\PushException
     */
    public function testSetMiddlePriority(): void
    {
        $push = $this->makePush()->setMiddlePriority();

        self::assertEquals(Push::PRIORITY_MIDDLE, $push->getPriority());
    }

    /**
     * @covers \ArtARTs36\PushAllSender\Push::setMinPriority
     * @throws \ArtARTs36\PushAllSender\Exceptions\PushException
     */
    public function testSetMinPriority(): void
    {
        $push = $this->makePush()->setMinPriority();

        self::assertEquals(Push::PRIORITY_MIN, $push->getPriority());
    }

    /**
     * @covers \ArtARTs36\PushAllSender\Push::getRecipientId
     * @throws \ArtARTs36\PushAllSender\Exceptions\PushException
     */
    public function testGetRecipientId(): void
    {
        $push = $this->makePush();

        self::assertNull($push->getRecipientId());

        //

        $recipient = new class implements PushRecipientInterface {
            /**
             * @inheritDoc
             */
            public function getPushAllId(): int
            {
                return 5;
            }
        };

        $push = new Push('Title', 'Message', $recipient);

        self::assertEquals(5, $push->getRecipientId());
    }

    /**
     * @covers \ArtARTs36\PushAllSender\Push::getPriority
     */
    public function testGetPriority(): void
    {
        $defaultStrategy = new NightMinPriorityStrategy();

        $push = $this->makePush();

        self::assertEquals($defaultStrategy->getPriority(), $push->getPriority());
    }

    /**
     * @return Push
     * @throws \ArtARTs36\PushAllSender\Exceptions\PushException
     */
    protected function makePush(): Push
    {
        return new Push('Title', 'Message');
    }
}
